DROP TABLE IF EXISTS model;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS clubs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users_permissions;
DROP TABLE IF EXISTS permissions;

